// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(tantivyFFI)
import tantivyFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_tantivy_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_tantivy_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureTantivyInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol TantivyIndexProtocol: AnyObject, Sendable {
    
    func clearIndex() throws 
    
    func commit() throws 
    
    func deleteDoc(id: DocumentField) throws 
    
    func docExists(id: DocumentField) throws  -> Bool
    
    func docsCount()  -> UInt64
    
    func getDoc(id: DocumentField) throws  -> TantivyDocumentFields
    
    func getDocsByIds(ids: [DocumentField]) throws  -> [TantivyDocumentFields]
    
    func indexDoc(doc: TantivyDocumentFields) throws 
    
    func indexDocs(docs: [TantivyDocumentFields]) throws 
    
    func search(query: TantivySearchQuery) throws  -> TantivySearchResults
    
    func searchDocIds(query: TantivySearchQuery, idField: String) throws  -> [TantivySearchHit]
    
    func searchDsl(queryJson: String, topDocLimit: UInt32, topDocOffset: UInt32) throws  -> TantivySearchResults
    
}
open class TantivyIndex: TantivyIndexProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_tantivy_fn_clone_tantivyindex(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_tantivy_fn_free_tantivyindex(handle, $0) }
    }

    
public static func newWithSchema(path: String, schemaBuilder: TantivySchemaBuilder)throws  -> TantivyIndex  {
    return try  FfiConverterTypeTantivyIndex_lift(try rustCallWithError(FfiConverterTypeTantivyIndexError_lift) {
    uniffi_tantivy_fn_constructor_tantivyindex_new_with_schema(
        FfiConverterString.lower(path),
        FfiConverterTypeTantivySchemaBuilder_lower(schemaBuilder),$0
    )
})
}
    

    
open func clearIndex()throws   {try rustCallWithError(FfiConverterTypeTantivyIndexError_lift) {
    uniffi_tantivy_fn_method_tantivyindex_clear_index(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func commit()throws   {try rustCallWithError(FfiConverterTypeTantivyIndexError_lift) {
    uniffi_tantivy_fn_method_tantivyindex_commit(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func deleteDoc(id: DocumentField)throws   {try rustCallWithError(FfiConverterTypeTantivyIndexError_lift) {
    uniffi_tantivy_fn_method_tantivyindex_delete_doc(
            self.uniffiCloneHandle(),
        FfiConverterTypeDocumentField_lower(id),$0
    )
}
}
    
open func docExists(id: DocumentField)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeTantivyIndexError_lift) {
    uniffi_tantivy_fn_method_tantivyindex_doc_exists(
            self.uniffiCloneHandle(),
        FfiConverterTypeDocumentField_lower(id),$0
    )
})
}
    
open func docsCount() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_tantivy_fn_method_tantivyindex_docs_count(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getDoc(id: DocumentField)throws  -> TantivyDocumentFields  {
    return try  FfiConverterTypeTantivyDocumentFields_lift(try rustCallWithError(FfiConverterTypeTantivyIndexError_lift) {
    uniffi_tantivy_fn_method_tantivyindex_get_doc(
            self.uniffiCloneHandle(),
        FfiConverterTypeDocumentField_lower(id),$0
    )
})
}
    
open func getDocsByIds(ids: [DocumentField])throws  -> [TantivyDocumentFields]  {
    return try  FfiConverterSequenceTypeTantivyDocumentFields.lift(try rustCallWithError(FfiConverterTypeTantivyIndexError_lift) {
    uniffi_tantivy_fn_method_tantivyindex_get_docs_by_ids(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeDocumentField.lower(ids),$0
    )
})
}
    
open func indexDoc(doc: TantivyDocumentFields)throws   {try rustCallWithError(FfiConverterTypeTantivyIndexError_lift) {
    uniffi_tantivy_fn_method_tantivyindex_index_doc(
            self.uniffiCloneHandle(),
        FfiConverterTypeTantivyDocumentFields_lower(doc),$0
    )
}
}
    
open func indexDocs(docs: [TantivyDocumentFields])throws   {try rustCallWithError(FfiConverterTypeTantivyIndexError_lift) {
    uniffi_tantivy_fn_method_tantivyindex_index_docs(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeTantivyDocumentFields.lower(docs),$0
    )
}
}
    
open func search(query: TantivySearchQuery)throws  -> TantivySearchResults  {
    return try  FfiConverterTypeTantivySearchResults_lift(try rustCallWithError(FfiConverterTypeTantivyIndexError_lift) {
    uniffi_tantivy_fn_method_tantivyindex_search(
            self.uniffiCloneHandle(),
        FfiConverterTypeTantivySearchQuery_lower(query),$0
    )
})
}
    
open func searchDocIds(query: TantivySearchQuery, idField: String)throws  -> [TantivySearchHit]  {
    return try  FfiConverterSequenceTypeTantivySearchHit.lift(try rustCallWithError(FfiConverterTypeTantivyIndexError_lift) {
    uniffi_tantivy_fn_method_tantivyindex_search_doc_ids(
            self.uniffiCloneHandle(),
        FfiConverterTypeTantivySearchQuery_lower(query),
        FfiConverterString.lower(idField),$0
    )
})
}
    
open func searchDsl(queryJson: String, topDocLimit: UInt32, topDocOffset: UInt32)throws  -> TantivySearchResults  {
    return try  FfiConverterTypeTantivySearchResults_lift(try rustCallWithError(FfiConverterTypeTantivyIndexError_lift) {
    uniffi_tantivy_fn_method_tantivyindex_search_dsl(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(queryJson),
        FfiConverterUInt32.lower(topDocLimit),
        FfiConverterUInt32.lower(topDocOffset),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTantivyIndex: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = TantivyIndex

    public static func lift(_ handle: UInt64) throws -> TantivyIndex {
        return TantivyIndex(unsafeFromHandle: handle)
    }

    public static func lower(_ value: TantivyIndex) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TantivyIndex {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: TantivyIndex, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivyIndex_lift(_ handle: UInt64) throws -> TantivyIndex {
    return try FfiConverterTypeTantivyIndex.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivyIndex_lower(_ value: TantivyIndex) -> UInt64 {
    return FfiConverterTypeTantivyIndex.lower(value)
}






public protocol TantivySchemaBuilderProtocol: AnyObject, Sendable {
    
    func addBoolField(name: String, options: NumericFieldOptions) 
    
    func addBytesField(name: String, stored: Bool, fast: Bool, indexed: Bool) 
    
    func addDateField(name: String, options: DateFieldOptions) 
    
    func addF64Field(name: String, options: NumericFieldOptions) 
    
    func addFacetField(name: String, options: FacetFieldOptions) 
    
    func addI64Field(name: String, options: NumericFieldOptions) 
    
    func addJsonField(name: String, options: JsonFieldOptions) 
    
    func addTextField(name: String, options: TextFieldOptions) 
    
    func addU64Field(name: String, options: NumericFieldOptions) 
    
}
open class TantivySchemaBuilder: TantivySchemaBuilderProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_tantivy_fn_clone_tantivyschemabuilder(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_tantivy_fn_constructor_tantivyschemabuilder_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_tantivy_fn_free_tantivyschemabuilder(handle, $0) }
    }

    

    
open func addBoolField(name: String, options: NumericFieldOptions)  {try! rustCall() {
    uniffi_tantivy_fn_method_tantivyschemabuilder_add_bool_field(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterTypeNumericFieldOptions_lower(options),$0
    )
}
}
    
open func addBytesField(name: String, stored: Bool, fast: Bool, indexed: Bool)  {try! rustCall() {
    uniffi_tantivy_fn_method_tantivyschemabuilder_add_bytes_field(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterBool.lower(stored),
        FfiConverterBool.lower(fast),
        FfiConverterBool.lower(indexed),$0
    )
}
}
    
open func addDateField(name: String, options: DateFieldOptions)  {try! rustCall() {
    uniffi_tantivy_fn_method_tantivyschemabuilder_add_date_field(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterTypeDateFieldOptions_lower(options),$0
    )
}
}
    
open func addF64Field(name: String, options: NumericFieldOptions)  {try! rustCall() {
    uniffi_tantivy_fn_method_tantivyschemabuilder_add_f64_field(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterTypeNumericFieldOptions_lower(options),$0
    )
}
}
    
open func addFacetField(name: String, options: FacetFieldOptions)  {try! rustCall() {
    uniffi_tantivy_fn_method_tantivyschemabuilder_add_facet_field(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterTypeFacetFieldOptions_lower(options),$0
    )
}
}
    
open func addI64Field(name: String, options: NumericFieldOptions)  {try! rustCall() {
    uniffi_tantivy_fn_method_tantivyschemabuilder_add_i64_field(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterTypeNumericFieldOptions_lower(options),$0
    )
}
}
    
open func addJsonField(name: String, options: JsonFieldOptions)  {try! rustCall() {
    uniffi_tantivy_fn_method_tantivyschemabuilder_add_json_field(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterTypeJsonFieldOptions_lower(options),$0
    )
}
}
    
open func addTextField(name: String, options: TextFieldOptions)  {try! rustCall() {
    uniffi_tantivy_fn_method_tantivyschemabuilder_add_text_field(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterTypeTextFieldOptions_lower(options),$0
    )
}
}
    
open func addU64Field(name: String, options: NumericFieldOptions)  {try! rustCall() {
    uniffi_tantivy_fn_method_tantivyschemabuilder_add_u64_field(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterTypeNumericFieldOptions_lower(options),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTantivySchemaBuilder: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = TantivySchemaBuilder

    public static func lift(_ handle: UInt64) throws -> TantivySchemaBuilder {
        return TantivySchemaBuilder(unsafeFromHandle: handle)
    }

    public static func lower(_ value: TantivySchemaBuilder) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TantivySchemaBuilder {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: TantivySchemaBuilder, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivySchemaBuilder_lift(_ handle: UInt64) throws -> TantivySchemaBuilder {
    return try FfiConverterTypeTantivySchemaBuilder.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivySchemaBuilder_lower(_ value: TantivySchemaBuilder) -> UInt64 {
    return FfiConverterTypeTantivySchemaBuilder.lower(value)
}




public struct DateFieldOptions: Equatable, Hashable {
    public var indexed: Bool
    public var stored: Bool
    public var fast: Bool
    public var fieldnorms: Bool
    public var precision: TantivyDatePrecision

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(indexed: Bool, stored: Bool, fast: Bool, fieldnorms: Bool, precision: TantivyDatePrecision) {
        self.indexed = indexed
        self.stored = stored
        self.fast = fast
        self.fieldnorms = fieldnorms
        self.precision = precision
    }

    
}

#if compiler(>=6)
extension DateFieldOptions: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDateFieldOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DateFieldOptions {
        return
            try DateFieldOptions(
                indexed: FfiConverterBool.read(from: &buf), 
                stored: FfiConverterBool.read(from: &buf), 
                fast: FfiConverterBool.read(from: &buf), 
                fieldnorms: FfiConverterBool.read(from: &buf), 
                precision: FfiConverterTypeTantivyDatePrecision.read(from: &buf)
        )
    }

    public static func write(_ value: DateFieldOptions, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.indexed, into: &buf)
        FfiConverterBool.write(value.stored, into: &buf)
        FfiConverterBool.write(value.fast, into: &buf)
        FfiConverterBool.write(value.fieldnorms, into: &buf)
        FfiConverterTypeTantivyDatePrecision.write(value.precision, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDateFieldOptions_lift(_ buf: RustBuffer) throws -> DateFieldOptions {
    return try FfiConverterTypeDateFieldOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDateFieldOptions_lower(_ value: DateFieldOptions) -> RustBuffer {
    return FfiConverterTypeDateFieldOptions.lower(value)
}


/**
 * A single document field
 */
public struct DocumentField: Equatable, Hashable {
    public var name: String
    public var value: FieldValue

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, value: FieldValue) {
        self.name = name
        self.value = value
    }

    
}

#if compiler(>=6)
extension DocumentField: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDocumentField: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DocumentField {
        return
            try DocumentField(
                name: FfiConverterString.read(from: &buf), 
                value: FfiConverterTypeFieldValue.read(from: &buf)
        )
    }

    public static func write(_ value: DocumentField, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterTypeFieldValue.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocumentField_lift(_ buf: RustBuffer) throws -> DocumentField {
    return try FfiConverterTypeDocumentField.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocumentField_lower(_ value: DocumentField) -> RustBuffer {
    return FfiConverterTypeDocumentField.lower(value)
}


public struct FacetFieldOptions: Equatable, Hashable {
    public var stored: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(stored: Bool) {
        self.stored = stored
    }

    
}

#if compiler(>=6)
extension FacetFieldOptions: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFacetFieldOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FacetFieldOptions {
        return
            try FacetFieldOptions(
                stored: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FacetFieldOptions, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.stored, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFacetFieldOptions_lift(_ buf: RustBuffer) throws -> FacetFieldOptions {
    return try FfiConverterTypeFacetFieldOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFacetFieldOptions_lower(_ value: FacetFieldOptions) -> RustBuffer {
    return FfiConverterTypeFacetFieldOptions.lower(value)
}


public struct JsonFieldOptions: Equatable, Hashable {
    public var stored: Bool
    public var indexed: Bool
    public var fast: Bool
    public var tokenizer: TantivyTokenizer
    public var record: TantivyIndexRecordOption
    public var fieldnorms: Bool
    public var expandDots: Bool
    public var fastTokenizer: TantivyTokenizer?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(stored: Bool, indexed: Bool, fast: Bool, tokenizer: TantivyTokenizer, record: TantivyIndexRecordOption, fieldnorms: Bool, expandDots: Bool, fastTokenizer: TantivyTokenizer?) {
        self.stored = stored
        self.indexed = indexed
        self.fast = fast
        self.tokenizer = tokenizer
        self.record = record
        self.fieldnorms = fieldnorms
        self.expandDots = expandDots
        self.fastTokenizer = fastTokenizer
    }

    
}

#if compiler(>=6)
extension JsonFieldOptions: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJsonFieldOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JsonFieldOptions {
        return
            try JsonFieldOptions(
                stored: FfiConverterBool.read(from: &buf), 
                indexed: FfiConverterBool.read(from: &buf), 
                fast: FfiConverterBool.read(from: &buf), 
                tokenizer: FfiConverterTypeTantivyTokenizer.read(from: &buf), 
                record: FfiConverterTypeTantivyIndexRecordOption.read(from: &buf), 
                fieldnorms: FfiConverterBool.read(from: &buf), 
                expandDots: FfiConverterBool.read(from: &buf), 
                fastTokenizer: FfiConverterOptionTypeTantivyTokenizer.read(from: &buf)
        )
    }

    public static func write(_ value: JsonFieldOptions, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.stored, into: &buf)
        FfiConverterBool.write(value.indexed, into: &buf)
        FfiConverterBool.write(value.fast, into: &buf)
        FfiConverterTypeTantivyTokenizer.write(value.tokenizer, into: &buf)
        FfiConverterTypeTantivyIndexRecordOption.write(value.record, into: &buf)
        FfiConverterBool.write(value.fieldnorms, into: &buf)
        FfiConverterBool.write(value.expandDots, into: &buf)
        FfiConverterOptionTypeTantivyTokenizer.write(value.fastTokenizer, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJsonFieldOptions_lift(_ buf: RustBuffer) throws -> JsonFieldOptions {
    return try FfiConverterTypeJsonFieldOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJsonFieldOptions_lower(_ value: JsonFieldOptions) -> RustBuffer {
    return FfiConverterTypeJsonFieldOptions.lower(value)
}


public struct NumericFieldOptions: Equatable, Hashable {
    public var indexed: Bool
    public var stored: Bool
    public var fast: Bool
    public var fieldnorms: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(indexed: Bool, stored: Bool, fast: Bool, fieldnorms: Bool) {
        self.indexed = indexed
        self.stored = stored
        self.fast = fast
        self.fieldnorms = fieldnorms
    }

    
}

#if compiler(>=6)
extension NumericFieldOptions: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNumericFieldOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NumericFieldOptions {
        return
            try NumericFieldOptions(
                indexed: FfiConverterBool.read(from: &buf), 
                stored: FfiConverterBool.read(from: &buf), 
                fast: FfiConverterBool.read(from: &buf), 
                fieldnorms: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: NumericFieldOptions, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.indexed, into: &buf)
        FfiConverterBool.write(value.stored, into: &buf)
        FfiConverterBool.write(value.fast, into: &buf)
        FfiConverterBool.write(value.fieldnorms, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNumericFieldOptions_lift(_ buf: RustBuffer) throws -> NumericFieldOptions {
    return try FfiConverterTypeNumericFieldOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNumericFieldOptions_lower(_ value: NumericFieldOptions) -> RustBuffer {
    return FfiConverterTypeNumericFieldOptions.lower(value)
}


/**
 * A complete document (scalar fields only)
 */
public struct TantivyDocumentFields: Equatable, Hashable {
    public var fields: [DocumentField]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(fields: [DocumentField]) {
        self.fields = fields
    }

    
}

#if compiler(>=6)
extension TantivyDocumentFields: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTantivyDocumentFields: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TantivyDocumentFields {
        return
            try TantivyDocumentFields(
                fields: FfiConverterSequenceTypeDocumentField.read(from: &buf)
        )
    }

    public static func write(_ value: TantivyDocumentFields, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeDocumentField.write(value.fields, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivyDocumentFields_lift(_ buf: RustBuffer) throws -> TantivyDocumentFields {
    return try FfiConverterTypeTantivyDocumentFields.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivyDocumentFields_lower(_ value: TantivyDocumentFields) -> RustBuffer {
    return FfiConverterTypeTantivyDocumentFields.lower(value)
}


public struct TantivyFuzzyField: Equatable, Hashable {
    public var fieldName: String
    public var prefix: Bool
    public var distance: UInt8
    public var transposeCostOne: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(fieldName: String, prefix: Bool, distance: UInt8, transposeCostOne: Bool) {
        self.fieldName = fieldName
        self.prefix = prefix
        self.distance = distance
        self.transposeCostOne = transposeCostOne
    }

    
}

#if compiler(>=6)
extension TantivyFuzzyField: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTantivyFuzzyField: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TantivyFuzzyField {
        return
            try TantivyFuzzyField(
                fieldName: FfiConverterString.read(from: &buf), 
                prefix: FfiConverterBool.read(from: &buf), 
                distance: FfiConverterUInt8.read(from: &buf), 
                transposeCostOne: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: TantivyFuzzyField, into buf: inout [UInt8]) {
        FfiConverterString.write(value.fieldName, into: &buf)
        FfiConverterBool.write(value.prefix, into: &buf)
        FfiConverterUInt8.write(value.distance, into: &buf)
        FfiConverterBool.write(value.transposeCostOne, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivyFuzzyField_lift(_ buf: RustBuffer) throws -> TantivyFuzzyField {
    return try FfiConverterTypeTantivyFuzzyField.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivyFuzzyField_lower(_ value: TantivyFuzzyField) -> RustBuffer {
    return FfiConverterTypeTantivyFuzzyField.lower(value)
}


public struct TantivySearchHit: Equatable, Hashable {
    public var docId: UInt64
    public var score: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(docId: UInt64, score: Float) {
        self.docId = docId
        self.score = score
    }

    
}

#if compiler(>=6)
extension TantivySearchHit: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTantivySearchHit: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TantivySearchHit {
        return
            try TantivySearchHit(
                docId: FfiConverterUInt64.read(from: &buf), 
                score: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: TantivySearchHit, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.docId, into: &buf)
        FfiConverterFloat.write(value.score, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivySearchHit_lift(_ buf: RustBuffer) throws -> TantivySearchHit {
    return try FfiConverterTypeTantivySearchHit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivySearchHit_lower(_ value: TantivySearchHit) -> RustBuffer {
    return FfiConverterTypeTantivySearchHit.lower(value)
}


public struct TantivySearchQuery: Equatable, Hashable {
    public var queryStr: String
    public var defaultFields: [String]
    public var fuzzyFields: [TantivyFuzzyField]
    public var topDocLimit: UInt32
    public var topDocOffset: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(queryStr: String, defaultFields: [String], fuzzyFields: [TantivyFuzzyField], topDocLimit: UInt32, topDocOffset: UInt32) {
        self.queryStr = queryStr
        self.defaultFields = defaultFields
        self.fuzzyFields = fuzzyFields
        self.topDocLimit = topDocLimit
        self.topDocOffset = topDocOffset
    }

    
}

#if compiler(>=6)
extension TantivySearchQuery: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTantivySearchQuery: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TantivySearchQuery {
        return
            try TantivySearchQuery(
                queryStr: FfiConverterString.read(from: &buf), 
                defaultFields: FfiConverterSequenceString.read(from: &buf), 
                fuzzyFields: FfiConverterSequenceTypeTantivyFuzzyField.read(from: &buf), 
                topDocLimit: FfiConverterUInt32.read(from: &buf), 
                topDocOffset: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: TantivySearchQuery, into buf: inout [UInt8]) {
        FfiConverterString.write(value.queryStr, into: &buf)
        FfiConverterSequenceString.write(value.defaultFields, into: &buf)
        FfiConverterSequenceTypeTantivyFuzzyField.write(value.fuzzyFields, into: &buf)
        FfiConverterUInt32.write(value.topDocLimit, into: &buf)
        FfiConverterUInt32.write(value.topDocOffset, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivySearchQuery_lift(_ buf: RustBuffer) throws -> TantivySearchQuery {
    return try FfiConverterTypeTantivySearchQuery.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivySearchQuery_lower(_ value: TantivySearchQuery) -> RustBuffer {
    return FfiConverterTypeTantivySearchQuery.lower(value)
}


public struct TantivySearchResult: Equatable, Hashable {
    public var score: Float
    public var doc: TantivyDocumentFields

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(score: Float, doc: TantivyDocumentFields) {
        self.score = score
        self.doc = doc
    }

    
}

#if compiler(>=6)
extension TantivySearchResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTantivySearchResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TantivySearchResult {
        return
            try TantivySearchResult(
                score: FfiConverterFloat.read(from: &buf), 
                doc: FfiConverterTypeTantivyDocumentFields.read(from: &buf)
        )
    }

    public static func write(_ value: TantivySearchResult, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.score, into: &buf)
        FfiConverterTypeTantivyDocumentFields.write(value.doc, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivySearchResult_lift(_ buf: RustBuffer) throws -> TantivySearchResult {
    return try FfiConverterTypeTantivySearchResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivySearchResult_lower(_ value: TantivySearchResult) -> RustBuffer {
    return FfiConverterTypeTantivySearchResult.lower(value)
}


public struct TantivySearchResults: Equatable, Hashable {
    public var count: UInt64
    public var docs: [TantivySearchResult]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(count: UInt64, docs: [TantivySearchResult]) {
        self.count = count
        self.docs = docs
    }

    
}

#if compiler(>=6)
extension TantivySearchResults: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTantivySearchResults: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TantivySearchResults {
        return
            try TantivySearchResults(
                count: FfiConverterUInt64.read(from: &buf), 
                docs: FfiConverterSequenceTypeTantivySearchResult.read(from: &buf)
        )
    }

    public static func write(_ value: TantivySearchResults, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.count, into: &buf)
        FfiConverterSequenceTypeTantivySearchResult.write(value.docs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivySearchResults_lift(_ buf: RustBuffer) throws -> TantivySearchResults {
    return try FfiConverterTypeTantivySearchResults.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivySearchResults_lower(_ value: TantivySearchResults) -> RustBuffer {
    return FfiConverterTypeTantivySearchResults.lower(value)
}


public struct TextFieldOptions: Equatable, Hashable {
    public var tokenizer: TantivyTokenizer
    public var record: TantivyIndexRecordOption
    public var stored: Bool
    public var fast: Bool
    public var fieldnorms: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(tokenizer: TantivyTokenizer, record: TantivyIndexRecordOption, stored: Bool, fast: Bool, fieldnorms: Bool) {
        self.tokenizer = tokenizer
        self.record = record
        self.stored = stored
        self.fast = fast
        self.fieldnorms = fieldnorms
    }

    
}

#if compiler(>=6)
extension TextFieldOptions: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTextFieldOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TextFieldOptions {
        return
            try TextFieldOptions(
                tokenizer: FfiConverterTypeTantivyTokenizer.read(from: &buf), 
                record: FfiConverterTypeTantivyIndexRecordOption.read(from: &buf), 
                stored: FfiConverterBool.read(from: &buf), 
                fast: FfiConverterBool.read(from: &buf), 
                fieldnorms: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: TextFieldOptions, into buf: inout [UInt8]) {
        FfiConverterTypeTantivyTokenizer.write(value.tokenizer, into: &buf)
        FfiConverterTypeTantivyIndexRecordOption.write(value.record, into: &buf)
        FfiConverterBool.write(value.stored, into: &buf)
        FfiConverterBool.write(value.fast, into: &buf)
        FfiConverterBool.write(value.fieldnorms, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTextFieldOptions_lift(_ buf: RustBuffer) throws -> TextFieldOptions {
    return try FfiConverterTypeTextFieldOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTextFieldOptions_lower(_ value: TextFieldOptions) -> RustBuffer {
    return FfiConverterTypeTextFieldOptions.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * A field value passed from Swift - no JSON serialization needed
 */

public enum FieldValue: Equatable, Hashable {
    
    case text(String
    )
    case u64(UInt64
    )
    case i64(Int64
    )
    case f64(Double
    )
    case bool(Bool
    )
    /**
     * Unix timestamp in microseconds
     */
    case date(Int64
    )
    case bytes(Data
    )
    case facet(String
    )
    case json(String
    )



}

#if compiler(>=6)
extension FieldValue: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFieldValue: FfiConverterRustBuffer {
    typealias SwiftType = FieldValue

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FieldValue {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .text(try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .u64(try FfiConverterUInt64.read(from: &buf)
        )
        
        case 3: return .i64(try FfiConverterInt64.read(from: &buf)
        )
        
        case 4: return .f64(try FfiConverterDouble.read(from: &buf)
        )
        
        case 5: return .bool(try FfiConverterBool.read(from: &buf)
        )
        
        case 6: return .date(try FfiConverterInt64.read(from: &buf)
        )
        
        case 7: return .bytes(try FfiConverterData.read(from: &buf)
        )
        
        case 8: return .facet(try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .json(try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FieldValue, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .text(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .u64(v1):
            writeInt(&buf, Int32(2))
            FfiConverterUInt64.write(v1, into: &buf)
            
        
        case let .i64(v1):
            writeInt(&buf, Int32(3))
            FfiConverterInt64.write(v1, into: &buf)
            
        
        case let .f64(v1):
            writeInt(&buf, Int32(4))
            FfiConverterDouble.write(v1, into: &buf)
            
        
        case let .bool(v1):
            writeInt(&buf, Int32(5))
            FfiConverterBool.write(v1, into: &buf)
            
        
        case let .date(v1):
            writeInt(&buf, Int32(6))
            FfiConverterInt64.write(v1, into: &buf)
            
        
        case let .bytes(v1):
            writeInt(&buf, Int32(7))
            FfiConverterData.write(v1, into: &buf)
            
        
        case let .facet(v1):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .json(v1):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFieldValue_lift(_ buf: RustBuffer) throws -> FieldValue {
    return try FfiConverterTypeFieldValue.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFieldValue_lower(_ value: FieldValue) -> RustBuffer {
    return FfiConverterTypeFieldValue.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum TantivyDatePrecision: Equatable, Hashable {
    
    case seconds
    case milliseconds
    case microseconds



}

#if compiler(>=6)
extension TantivyDatePrecision: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTantivyDatePrecision: FfiConverterRustBuffer {
    typealias SwiftType = TantivyDatePrecision

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TantivyDatePrecision {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .seconds
        
        case 2: return .milliseconds
        
        case 3: return .microseconds
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TantivyDatePrecision, into buf: inout [UInt8]) {
        switch value {
        
        
        case .seconds:
            writeInt(&buf, Int32(1))
        
        
        case .milliseconds:
            writeInt(&buf, Int32(2))
        
        
        case .microseconds:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivyDatePrecision_lift(_ buf: RustBuffer) throws -> TantivyDatePrecision {
    return try FfiConverterTypeTantivyDatePrecision.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivyDatePrecision_lower(_ value: TantivyDatePrecision) -> RustBuffer {
    return FfiConverterTypeTantivyDatePrecision.lower(value)
}



public enum TantivyIndexError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case IoError(message: String)
    
    case OpenDirectoryError(message: String)
    
    case TantivyError(message: String)
    
    case SerializationError(message: String)
    
    case DocParsingError(message: String)
    
    case FacetParseError(message: String)
    
    case TryFromIntError(message: String)
    
    case WriterAcquisitionError(message: String)
    
    case DocRetrievalError(message: String)
    
    case SchemaBuilderError(message: String)
    
    case QueryError(message: String)
    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension TantivyIndexError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTantivyIndexError: FfiConverterRustBuffer {
    typealias SwiftType = TantivyIndexError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TantivyIndexError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .IoError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .OpenDirectoryError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .TantivyError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .SerializationError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .DocParsingError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .FacetParseError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .TryFromIntError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .WriterAcquisitionError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .DocRetrievalError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 10: return .SchemaBuilderError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 11: return .QueryError(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TantivyIndexError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .IoError(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .OpenDirectoryError(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .TantivyError(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .SerializationError(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .DocParsingError(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .FacetParseError(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .TryFromIntError(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))
        case .WriterAcquisitionError(_ /* message is ignored*/):
            writeInt(&buf, Int32(8))
        case .DocRetrievalError(_ /* message is ignored*/):
            writeInt(&buf, Int32(9))
        case .SchemaBuilderError(_ /* message is ignored*/):
            writeInt(&buf, Int32(10))
        case .QueryError(_ /* message is ignored*/):
            writeInt(&buf, Int32(11))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivyIndexError_lift(_ buf: RustBuffer) throws -> TantivyIndexError {
    return try FfiConverterTypeTantivyIndexError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivyIndexError_lower(_ value: TantivyIndexError) -> RustBuffer {
    return FfiConverterTypeTantivyIndexError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum TantivyIndexRecordOption: Equatable, Hashable {
    
    case basic
    case withFreqs
    case withFreqsAndPositions



}

#if compiler(>=6)
extension TantivyIndexRecordOption: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTantivyIndexRecordOption: FfiConverterRustBuffer {
    typealias SwiftType = TantivyIndexRecordOption

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TantivyIndexRecordOption {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .basic
        
        case 2: return .withFreqs
        
        case 3: return .withFreqsAndPositions
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TantivyIndexRecordOption, into buf: inout [UInt8]) {
        switch value {
        
        
        case .basic:
            writeInt(&buf, Int32(1))
        
        
        case .withFreqs:
            writeInt(&buf, Int32(2))
        
        
        case .withFreqsAndPositions:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivyIndexRecordOption_lift(_ buf: RustBuffer) throws -> TantivyIndexRecordOption {
    return try FfiConverterTypeTantivyIndexRecordOption.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivyIndexRecordOption_lower(_ value: TantivyIndexRecordOption) -> RustBuffer {
    return FfiConverterTypeTantivyIndexRecordOption.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum TantivyTokenizer: Equatable, Hashable {
    
    case raw
    case `default`
    case unicode
    case enStem
    case whitespace



}

#if compiler(>=6)
extension TantivyTokenizer: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTantivyTokenizer: FfiConverterRustBuffer {
    typealias SwiftType = TantivyTokenizer

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TantivyTokenizer {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .raw
        
        case 2: return .`default`
        
        case 3: return .unicode
        
        case 4: return .enStem
        
        case 5: return .whitespace
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TantivyTokenizer, into buf: inout [UInt8]) {
        switch value {
        
        
        case .raw:
            writeInt(&buf, Int32(1))
        
        
        case .`default`:
            writeInt(&buf, Int32(2))
        
        
        case .unicode:
            writeInt(&buf, Int32(3))
        
        
        case .enStem:
            writeInt(&buf, Int32(4))
        
        
        case .whitespace:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivyTokenizer_lift(_ buf: RustBuffer) throws -> TantivyTokenizer {
    return try FfiConverterTypeTantivyTokenizer.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTantivyTokenizer_lower(_ value: TantivyTokenizer) -> RustBuffer {
    return FfiConverterTypeTantivyTokenizer.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeTantivyTokenizer: FfiConverterRustBuffer {
    typealias SwiftType = TantivyTokenizer?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeTantivyTokenizer.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeTantivyTokenizer.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDocumentField: FfiConverterRustBuffer {
    typealias SwiftType = [DocumentField]

    public static func write(_ value: [DocumentField], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDocumentField.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DocumentField] {
        let len: Int32 = try readInt(&buf)
        var seq = [DocumentField]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDocumentField.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTantivyDocumentFields: FfiConverterRustBuffer {
    typealias SwiftType = [TantivyDocumentFields]

    public static func write(_ value: [TantivyDocumentFields], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTantivyDocumentFields.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TantivyDocumentFields] {
        let len: Int32 = try readInt(&buf)
        var seq = [TantivyDocumentFields]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTantivyDocumentFields.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTantivyFuzzyField: FfiConverterRustBuffer {
    typealias SwiftType = [TantivyFuzzyField]

    public static func write(_ value: [TantivyFuzzyField], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTantivyFuzzyField.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TantivyFuzzyField] {
        let len: Int32 = try readInt(&buf)
        var seq = [TantivyFuzzyField]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTantivyFuzzyField.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTantivySearchHit: FfiConverterRustBuffer {
    typealias SwiftType = [TantivySearchHit]

    public static func write(_ value: [TantivySearchHit], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTantivySearchHit.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TantivySearchHit] {
        let len: Int32 = try readInt(&buf)
        var seq = [TantivySearchHit]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTantivySearchHit.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTantivySearchResult: FfiConverterRustBuffer {
    typealias SwiftType = [TantivySearchResult]

    public static func write(_ value: [TantivySearchResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTantivySearchResult.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TantivySearchResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [TantivySearchResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTantivySearchResult.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_tantivy_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyindex_clear_index() != 27081) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyindex_commit() != 43767) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyindex_delete_doc() != 42366) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyindex_doc_exists() != 46277) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyindex_docs_count() != 27948) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyindex_get_doc() != 36267) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyindex_get_docs_by_ids() != 15134) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyindex_index_doc() != 42651) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyindex_index_docs() != 51417) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyindex_search() != 50109) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyindex_search_doc_ids() != 800) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyindex_search_dsl() != 49563) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyschemabuilder_add_bool_field() != 55377) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyschemabuilder_add_bytes_field() != 13557) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyschemabuilder_add_date_field() != 15444) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyschemabuilder_add_f64_field() != 22613) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyschemabuilder_add_facet_field() != 19837) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyschemabuilder_add_i64_field() != 12775) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyschemabuilder_add_json_field() != 16732) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyschemabuilder_add_text_field() != 21373) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_method_tantivyschemabuilder_add_u64_field() != 28559) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_constructor_tantivyindex_new_with_schema() != 52043) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tantivy_checksum_constructor_tantivyschemabuilder_new() != 16789) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureTantivyInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all